version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: "/myapp/docker-credentials/username"
    DOCKER_REGISTRY_PASSWORD: "/myapp/docker-credentials/password"
    DOCKER_REGISTRY_URL: "/myapp/docker-registry/url"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python dependencies"
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Logging in to Docker registry..."
      - echo "Registry URL: $DOCKER_REGISTRY_URL"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t simple-python-app .
      - docker tag simple-python-app:latest "$DOCKER_REGISTRY_USERNAME/simple-python-app:latest"

  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push "$DOCKER_REGISTRY_USERNAME/simple-python-app:latest"
      - echo "Build and push completed successfully!"

artifacts:
  files:
    - "**/*"

